### ISSUE TITLE
Can't pass class props to some components

### ISSUE THREAD

**Issue by epavanello** [illright/attractions#333] opened 2021-12-31 16:11 UTC
Hi, great work for that library!
I saw that I can't pass class prop to Chip component also if it's defined but I don't found in the soruces the cause 🤦🏽‍♂️
![image](https://user-images.githubusercontent.com/47756116/147831932-4d1c1d33-43f6-47a0-87c5-786a9aaf4cc9.png)

**Comment by illright** [comment] 2021-12-31 16:16
Hi! Could you please paste the error message that your editor gives you when you try to pass this class? Off the top of my head, I see no reason why it shouldn't work.

Also, are you using TypeScript?

**Comment by aabounegm** [comment] 2021-12-31 16:17
The issue seems to be with TypeScript typings, since the prop is defined. The library we use to generate the types ([sveld](https://www.npmjs.com/package/sveld)) was not able to handle the way we define the `class` prop (exporting a renamed variable), but we will check if the issue is fixed or try to come up with a workaround as soon as we can.

**Comment by epavanello** [comment] 2021-12-31 18:32
I've found the difference between the two components, the first works only because TextField inherits props from htmlInput and Chip doesn't inherit nothing.
So, the bug seems to be the typescript type generator that ignore class props.

**Comment by epavanello** [comment] 2021-12-31 18:34
It seems related to this issue:

https://github.com/carbon-design-system/sveld/issues/50

**Comment by epavanello** [comment] 2021-12-31 20:54
> Hi! Could you please paste the error message that your editor gives you when you try to pass this class? Off the top of my head, I see no reason why it shouldn't work.
> 
> Also, are you using TypeScript?

Now I'm not on the pc, the error is class prop missing, and the d.ts file generated associated hasn't that prop, seems a bug of svelted

**Comment by aabounegm** [comment] 2022-01-01 17:33
> It seems related to this issue:
> 
> [carbon-design-system/sveld#50](https://github.com/carbon-design-system/sveld/issues/50)

> seems a bug of sveld that ignore class props

That is indeed the issue. I tried it and it seems like Sveld still does not pick up on prop aliases, and I cannot think of an easy way around that. It also sometimes doesn't make sense to use `{...$$restProps}` in some components (especially ones with more than one root element), so this workaround may not always fit.
Unfortunately, there is nothing we can do until this is fixed on their side.

**Comment by epavanello** [comment] 2022-01-01 17:44
Soon I'll try to fix the sveld bug

**Comment by aabounegm** [comment] 2022-01-02 00:08
@epavanello That's alright. I had some time and took a shot at it with https://github.com/carbon-design-system/sveld/pull/62 :)

**Closed** 2022-01-12 14:10 UTC
