### ISSUE TITLE
Mobile bug: a dropdown should close when navigating to a new page or, in general, when it loses focus

### ISSUE THREAD

**Issue by elimisteve** [illright/attractions#134] opened 2020-08-24 00:56 UTC

**Comment by elimisteve** [comment] 2020-08-24 00:56
As mentioned here: https://old.reddit.com/r/sveltejs/comments/ieexhf/attractions_a_new_minimal_ui_components_library/g2n7e0k/

**Comment by aabounegm** [comment] 2020-08-24 06:03
The cause is related to the same problem outlined in #133. A fix for this has already been started.

**Closed** 2020-08-24 17:55 UTC
Labels: bug, documentation
